[package]
org = "ballerinax"
name = "azure_functions"
version = "3.3.1"
distribution = "2201.5.0"
repository = "https://github.com/ballerina-platform/module-ballerinax-azure.functions"
license = ["Apache-2.0"]
keywords = ["azure", "functions", "serverless", "cloud"]

[[platform.java11.dependency]]
path = "../native/build/libs/azure_functions-native-3.3.1-SNAPSHOT.jar"

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "mime-native"
version = "2.7.0"
path = "./lib/mime-native-2.7.0.jar"
