[package]
org = "ballerinax"
name = "azure.functions"
version = "4.1.0"
distribution = "2201.8.0"
repository = "https://github.com/ballerina-platform/module-ballerinax-azure.functions"
license = ["Apache-2.0"]
keywords = ["azure", "functions", "serverless", "cloud"]

[platform.java17]
graalvmCompatible = true

[[platform.java17.dependency]]
path = "../native/build/libs/azure.functions-native-4.1.0-SNAPSHOT.jar"

[[platform.java17.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "mime-native"
version = "2.9.0"
path = "./lib/mime-native-2.9.0.jar"
