[plugin]
id = "azure-functions"
class = "org.ballerinax.azurefunctions.generator.AzureCompilerPlugin"

[[dependency]]
path = "../compiler-plugin/build/libs/azure_functions-compiler-plugin-2.0.2-SNAPSHOT.jar"
